// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSdzybZWw_aL9DnoIeADQiKdEFbjPt0eY',
    appId: '1:1029771182282:web:49179c32c23a61066cf433',
    messagingSenderId: '1029771182282',
    projectId: 'notificaciones-6804d',
    authDomain: 'notificaciones-6804d.firebaseapp.com',
    storageBucket: 'notificaciones-6804d.appspot.com',
    measurementId: 'G-5Y3BXE89DH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzXPKzIUJDTMo07q8QoeHTjbRRT6X6aGM',
    appId: '1:1029771182282:android:767df7a357d89d2a6cf433',
    messagingSenderId: '1029771182282',
    projectId: 'notificaciones-6804d',
    storageBucket: 'notificaciones-6804d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByK5qNZzKxROwGyK-iju0Kg8zyJjiVrsU',
    appId: '1:1029771182282:ios:289fa195664d07c16cf433',
    messagingSenderId: '1029771182282',
    projectId: 'notificaciones-6804d',
    storageBucket: 'notificaciones-6804d.appspot.com',
    iosClientId: '1029771182282-2s2tppggfshbpb7hd02mnj8a6jd04njv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterNotificaciones',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByK5qNZzKxROwGyK-iju0Kg8zyJjiVrsU',
    appId: '1:1029771182282:ios:289fa195664d07c16cf433',
    messagingSenderId: '1029771182282',
    projectId: 'notificaciones-6804d',
    storageBucket: 'notificaciones-6804d.appspot.com',
    iosClientId: '1029771182282-2s2tppggfshbpb7hd02mnj8a6jd04njv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterNotificaciones',
  );
}
